### ISSUE TITLE
print-manifest-arch-digest.sh: Simplied

### ISSUE THREAD

**Issue by davidgraeff** [junaruga/ci-multi-arch-test#45]
Just came from https://github.com/containers/buildah/issues/1590

https://github.com/junaruga/ci-multi-arch-test/blob/f3b242f8dccfded045d8a347bd71333e53eb2663/script/print-manifest-arch-digest.sh#L16

This and all the following lines can be condensed into a single line:
```
skopeo inspect --raw "docker://${BASE_IMAGE}" | jq -r ".manifests[] | select(.platform.architecture == \"${MANIFEST_ARCH}\") | .digest"
```

which simplifies the script in your comment at https://github.com/containers/buildah/issues/1590#issuecomment-531600564.

Hopefully podman just gains "--platform" and "buildx" support at some point.

**Comment by junaruga** [comment]
@davidgraeff Hi David, thank you for your suggestion. Your way looks better than mine.
Is it possible to send the pull-request to this repository if you do not mind?

Yeah, I am also looking forward to seeing the podman "--platform" and "buildx" support.
